staging-settings:
  user-workflow:
    workflow-name: "domino-effect-market-generator"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.staging.json"
    secrets-path: "./secrets.yaml"  
  capabilities:
    http:
      allowed-domains:
        - "generativelanguage.googleapis.com"
        - "api.pinata.cloud"
        - "www.reddit.com"
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: "https://ethereum-sepolia-rpc.publicnode.com"